version: '3.8'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    environment:
      MYSQL_DATABASE: techjobs
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
        - c:\techjobs\db:/var/lib/mysql
    ports:
      - "33061:3306"